[package]
name = "transliteration"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
combine = "4.6.4"
icu_properties = { version = "1.2.0", path = "../../components/properties" }
icu_collections = { version = "1.2.0", path = "../../components/collections", features = ["serde"] }
icu_unicodeset_parser = { path = "../unicodeset_parser", features = ["compiled_data"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
zerovec = { version = "0.9.4", path = "../../utils/zerovec", features = ["yoke", "derive"] }
zerofrom = { version = "0.1.1", path = "../../utils/zerofrom", features = ["derive"] }

