[package]
name = "icu_unicodeset_parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
icu_collections = { path = "../../components/collections" }
icu_properties = { path = "../../components/properties" }
icu_provider = { path = "../../provider/core" }

serde = { version = "1.0", features = ["derive", "alloc"], optional = true, default-features = false }
tinystr = { version = "0.7.1", path = "../../utils/tinystr", default-features = false, features = ["alloc", "zerovec"] }
zerovec = { version = "0.9.4", path = "../../utils/zerovec",  features = ["yoke"] }
databake = { version = "0.1.3", path = "../../utils/databake", optional = true, features = ["derive"] }
displaydoc = { version = "0.2.3", default-features = false }
icu_testdata = { version = "1.2.0", path = "../../provider/testdata" }

[features]
default = []
std = []
bench = ["serde"]
serde = ["dep:serde", "tinystr/serde", "zerovec/serde", "icu_provider/serde"]
datagen = ["serde", "dep:databake", "zerovec/databake", "tinystr/databake"]
experimental = []
